### PR TITLE
Initialize core before handle received broadcast

### LINKED ISSUE #86: Android: attempt to invoke android.content.Context.getApplicationContext() on a null object reference
```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.mapswithme.maps.location.TrackRecorderWakeReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4238)
       at android.app.ActivityThread.access$1700(ActivityThread.java:274)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2113)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
       at com.mapswithme.maps.MwmApplication.backgroundTracker(MwmApplication.java:129)
       at com.mapswithme.maps.location.TrackRecorder.onWakeAlarm(TrackRecorder.java:160)
       at com.mapswithme.maps.location.TrackRecorderWakeReceiver.onReceive(TrackRecorderWakeReceiver.java:26)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4229)
       at android.app.ActivityThread.access$1700(ActivityThread.java:274)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2113)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
```

https://console.firebase.google.com/u/0/project/omapsapp/crashlytics/app/android:app.omaps.beta/issues/8da9405ad6b9caccd22c4b5c55366641?time=last-seven-days&sessionEventKey=602BF7B800E300012356CC52B104BACB_1508350428385340551

### PR DESCRIPTION
**Pull request by int02h**
Sometimes we can receive broadcast before the core is managed to be initialized. In this case, we need to initialize it.

closes #86

### CODE REVIEW

File: android/src/com/mapswithme/maps/background/AbstractLogBroadcastReceiver.java [hunk 1]
```diff
@@ -1,25 +1,25 @@
...
+
+import com.mapswithme.maps.MwmBroadcastReceiver;
 import com.mapswithme.util.CrashlyticsUtils;
 import com.mapswithme.util.log.Logger;
 import com.mapswithme.util.log.LoggerFactory;
 
 import static com.mapswithme.maps.MwmApplication.backgroundTracker;
 
-public abstract class AbstractLogBroadcastReceiver extends BroadcastReceiver
+public abstract class AbstractLogBroadcastReceiver extends MwmBroadcastReceiver
```
Comment (alexzatsepin) [inline android/src/com/mapswithme/maps/background/AbstractLogBroadcastReceiver.java:17]: I wouldn't make all broadcast receivers descendants of MwmBroadcasReceiver, because not all needs in a heavyweight core. If you know specific case where is problem encountered I would prefer fix only that case. Could you provide the case in which the problem appears?

File: android/src/com/mapswithme/maps/MwmBroadcastReceiver.java [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+
+    protected abstract void onReceiveInitialized(Context context, Intent intent);
+
+    @Override
+    public final void onReceive(Context context, Intent intent)
+    {
+        MwmApplication app = MwmApplication.from(context);
+        if (!app.arePlatformAndCoreInitialized())
+        {
+            app.initCore();
```
Comment (alexzatsepin) [inline android/src/com/mapswithme/maps/MwmBroadcastReceiver.java:17]: You should check returned value from initcore method, there is case when we cannot create dirs on file system and show error dialog to the user on application start, otherwise the crash will happen.

```
if (!app.arePlatformAndCoreInitialized() && !app.initCore())
    return;
```

File: android/src/com/mapswithme/maps/MwmBroadcastReceiver.java [hunk 3]
```diff
@@ -0,0 +1,22 @@
+package com.mapswithme.maps;
+
+import android.content.BroadcastReceiver;
+import android.content.Context;
+import android.content.Intent;
+
+public abstract class MwmBroadcastReceiver extends BroadcastReceiver {
+
+    protected abstract void onReceiveInitialized(Context context, Intent intent);
```
Comment (alexzatsepin) [inline android/src/com/mapswithme/maps/MwmBroadcastReceiver.java:9]: Add @nonnull annotations to parameters please

File: android/src/com/mapswithme/maps/background/AbstractLogBroadcastReceiver.java (hunk 1 above)
Comment (int02h) [reply android/src/com/mapswithme/maps/background/AbstractLogBroadcastReceiver.java:17]: Rollback some receivers

File: android/src/com/mapswithme/maps/MwmBroadcastReceiver.java (hunk 3 above)
Comment (int02h) [reply android/src/com/mapswithme/maps/MwmBroadcastReceiver.java:9]: I've tried to do that but in this case there is a warning saying that parameters in super class are not annotated as `@NonNull`. As I remember at least `intent` can be `null`.

Comment (alexzatsepin) [reply android/src/com/mapswithme/maps/MwmBroadcastReceiver.java:9]: You are right, intent might be null. But as long as onRecieveInitialized is our method we can explicitly make "nullness" contract by ourself. If we decide to pass intent as non-null only you can check it on null before calling the onReceiveInitialized method either we can mark it @Nullable, both options are looked good for me besides the leaving parameters without annotations. I would want to follow our practise which we introduced in mapsme: mark all reference type parameters and fields with nullness annotations (where it's not obvious what value can be come from android sdk or from somewhere - it's good reason to mark as @Nullable, i.e. be prepared to process null in runtime)

Comment (alexzatsepin) [reply android/src/com/mapswithme/maps/MwmBroadcastReceiver.java:9]: As for context - it's should be @nonnull.

Comment (rtsisyk) [reply android/src/com/mapswithme/maps/MwmBroadcastReceiver.java:9]: Any news here? I removed a lot of code by #199. Please re-check.

Comment (int02h) [reply android/src/com/mapswithme/maps/MwmBroadcastReceiver.java]: @alexzatsepin annotations have been added

Comment (int02h) [reply android/src/com/mapswithme/maps/MwmBroadcastReceiver.java]: @rtsisyk I've rebased on master. Everything is fine.

**Review by rtsisyk — APPROVED** [review]
LGTM. I think it should fix #205.

**Comment by rtsisyk** [comment]
Merged. Thanks!

**Comment by biodranik** [comment]
@int02h what are these cases?
